# Generated by Django 4.0.4 on 2023-12-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagram',
            name='percent',
            field=models.IntegerField(blank=True, default=0.0),
        ),
    ]
