# Generated by Django 4.0.4 on 2023-12-16 06:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_userprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 16, 12, 50, 26, 305519))),
                ('profit', models.FloatField(blank=True, default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='invest_sum',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.CreateModel(
            name='UserTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 16, 12, 50, 26, 305519))),
                ('withdrawal', models.FloatField(blank=True, default=0.0)),
                ('userprofit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofit')),
            ],
        ),
        migrations.AddField(
            model_name='userprofit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.userprofile'),
        ),
    ]
