# Generated by Django 4.0.4 on 2023-12-16 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_userprofit_date_alter_usertransaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofit',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 16, 13, 0, 47, 274623)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 16, 13, 0, 47, 274623)),
        ),
    ]
