# Generated by Django 4.0.4 on 2023-12-16 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_userprofit_date_alter_usertransaction_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransaction',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofit',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 17, 5, 1, 56, 31954)),
        ),
        migrations.AlterField(
            model_name='usertransaction',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 17, 5, 1, 56, 31954)),
        ),
    ]
